const fs = require('fs');
let lines = fs.readFileSync('admin/staff.html', 'utf8').split('\n');
lines[1142] = '                            </div>` : \'\'}';
lines[1143] = '                            <div class="staff-info" style="margin-top:8px;">';
lines[1146] = '                            </div>';
lines[1147] = '                            <button class="availability-toggle ${member.isAvailable ? \'available\' : \'unavailable\'}"';
lines[1148] = '                                    onclick="toggleAvailability(\'${member._id}\')">';
lines[1149] = '                                ${member.isAvailable ? \'<i class="fas fa-check"></i> Available\' : \'<i class="fas fa-times"></i> Unavailable\'}';
lines[1150] = '                            </button>';
lines[1151] = '                            <div class="staff-actions">';
lines[1152] = '                                <button class="action-btn" onclick="deleteStaff(\'${member._id}\')" style="background: var(--accent-danger); margin-top: 8px;">Delete Access</button>';
lines[1153] = '                            </div>';
fs.writeFileSync('admin/staff.html', lines.join('\n'));
console.log('Done');
