const fs = require('fs');
let content = fs.readFileSync('server.js', 'utf8');
const old1 = "require('./staff-routes/auth');";
const new1 = "require('./staff-system/routes/auth');";
const old2 = "require('./staff-routes/staff');";
const new2 = "require('./staff-system/routes/staff');";
const old3 = "require('./staff-routes/supervisor');";
const new3 = "require('./staff-system/routes/supervisor');";
const old4 = "require('./staff-routes/admin');";
const new4 = "require('./staff-system/routes/admin');";
const insertion = "const adminDashboardRoutes = require('./staff-system/routes/adminDashboardRoutes');\nconst adminStaffRoutes = require('./staff-system/routes/adminStaffRoutes');\nconst adminEventsRoutes = require('./staff-system/routes/adminEventsRoutes');\nconst adminFinanceRoutes = require('./staff-system/routes/adminFinanceRoutes');\nconst adminReportsRoutes = require('./staff-system/routes/adminReportsRoutes');\nconst adminLegacyRoutes = require('./staff-system/routes/admin');";
content = content.replace(old1, new1).replace(old2, new2).replace(old3, new3).replace(old4, new4 + "\n" + insertion);
const mountInsertion = "\napp.use('/portal/admin-staff', adminDashboardRoutes);\napp.use('/portal/admin-staff', adminStaffRoutes);\napp.use('/portal/admin-staff', adminEventsRoutes);\napp.use('/portal/admin-staff', adminFinanceRoutes);\napp.use('/portal/admin-staff', adminReportsRoutes);\napp.use('/portal/admin-staff', adminLegacyRoutes);";
content = content.replace("app.use('/portal/supervisor', portalSupervisorRoutes);", "app.use('/portal/supervisor', portalSupervisorRoutes);" + mountInsertion);
fs.writeFileSync('server.js', content);
console.log('Done');
