const fs = require('fs');
let lines = fs.readFileSync('admin/staff.html', 'utf8').split('\n');
lines[1140] = '                                <a href="https://wa.me/${member.whatsapp.replace(/\\D/g, \'\')}" target="_blank" style="color:#25D366;font-size:12px;text-decoration:none;font-weight:600;">';
lines[1141] = '                                    <i class="fas fa-comment"></i> Message on WhatsApp';
lines[1142] = '                                </a>';
lines[1155] = '                    </div>';
lines[1156] = '                \`';
lines[1157] = '                    }).join(\'\');';
lines[1158] = '                }';
fs.writeFileSync('admin/staff.html', lines.join('\n'));
console.log('Done');
