const fs = require('fs');
let lines = fs.readFileSync('admin/staff.html', 'utf8').split('\n');
lines[1137] = '                            ${member.whatsapp ? `';
lines[1138] = '                            <div class="staff-info" style="margin-top:4px;">';
lines[1139] = '                                <span class="staff-label">WhatsApp:</span><br>';
lines[1140] = '                                <a href="https://wa.me/${member.whatsapp.replace(/\\D/g, \'\')}" target="_blank" style="color:#25D366;font-size:12px;text-decoration:none;font-weight:600;">';
lines[1141] = '                                    <i class="fas fa-comment"></i> Message on WhatsApp';
lines[1142] = '                                </a>';
lines[1143] = '                            </div>` : \'\'}';
fs.writeFileSync('admin/staff.html', lines.join('\n'));
console.log('Done');
